# Generated by Django 6.1.1 on 2026-09-23 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('signup', 'Signup'), ('module_created', 'Module created'), ('module_deleted', 'Module deleted'), ('quiz_hosted', 'Quiz hosted'), ('quiz_ended', 'Quiz ended'), ('quiz_joined', 'Quiz joined'), ('user_created', 'User created'), ('user_updated', 'User updated'), ('user_deleted', 'User deleted'), ('session_ended', 'Session ended'), ('report_downloaded', 'Report downloaded')], max_length=30)),
                ('target', models.CharField(blank=True, max_length=200)),
                ('details', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor', '-created_at'], name='quiz_activi_actor_i_01b585_idx'), models.Index(fields=['action', '-created_at'], name='quiz_activi_action_9955b7_idx')],
            },
        ),
    ]
