# Generated by Django 6.1.1 on 2026-09-23 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('signup', 'Signup'), ('module_created', 'Module created'), ('module_deleted', 'Module deleted'), ('quiz_hosted', 'Quiz hosted'), ('quiz_ended', 'Quiz ended'), ('quiz_joined', 'Quiz joined'), ('user_created', 'User created'), ('user_updated', 'User updated'), ('user_deleted', 'User deleted'), ('session_ended', 'Session ended'), ('report_downloaded', 'Report downloaded'), ('bank_added', 'Bank question imported'), ('question_banked', 'Question saved to bank')], max_length=30),
        ),
        migrations.CreateModel(
            name='BankQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('time_limit', models.PositiveIntegerField(default=30, help_text='Seconds')),
                ('points', models.PositiveIntegerField(default=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Bank questions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quiz.bankquestion')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
