# Generated by Django 6.1.1 on 2026-09-23 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_seed_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankquestion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]