# Generated by Django 6.1.1 on 2026-09-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_question_is_active_bankquestion_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='facebook',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='instagram',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='tiktok',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='youtube',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('signup', 'Signup'), ('module_created', 'Module created'), ('module_deleted', 'Module deleted'), ('quiz_hosted', 'Quiz hosted'), ('quiz_ended', 'Quiz ended'), ('quiz_joined', 'Quiz joined'), ('user_created', 'User created'), ('user_updated', 'User updated'), ('user_deleted', 'User deleted'), ('session_ended', 'Session ended'), ('report_downloaded', 'Report downloaded'), ('bank_added', 'Bank question imported'), ('question_banked', 'Question saved to bank'), ('profile_updated', 'Profile updated'), ('password_changed', 'Password changed')], max_length=30),
        ),
    ]
