# Generated by Django 6.1.1 on 2026-09-25 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_user_facebook_user_instagram_user_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankquestion',
            name='points',
        ),
        migrations.RemoveField(
            model_name='question',
            name='points',
        ),
    ]
