# Generated by Django 6.1.1 on 2026-09-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_remove_bankquestion_points_remove_question_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='practice_code',
            field=models.CharField(blank=True, editable=False, max_length=6),
        ),
        migrations.AddField(
            model_name='participant',
            name='team',
            field=models.CharField(blank=True, choices=[('red', 'Red'), ('blue', 'Blue'), ('yellow', 'Yellow'), ('green', 'Green')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='question_pause_remaining',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='teams_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
