# Generated by Django 6.1.1 on 2026-09-26 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_module_practice_code_participant_team_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='practice_code',
        ),
        migrations.AddField(
            model_name='participant',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Student account this play is linked to (progress tracking).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('signup', 'Signup'), ('code_generated', 'Registration codes generated'), ('module_created', 'Module created'), ('module_deleted', 'Module deleted'), ('quiz_hosted', 'Quiz hosted'), ('quiz_ended', 'Quiz ended'), ('quiz_joined', 'Quiz joined'), ('user_created', 'User created'), ('user_updated', 'User updated'), ('user_deleted', 'User deleted'), ('session_ended', 'Session ended'), ('report_downloaded', 'Report downloaded'), ('bank_added', 'Bank question imported'), ('question_banked', 'Question saved to bank'), ('profile_updated', 'Profile updated'), ('password_changed', 'Password changed')], max_length=30),
        ),
        migrations.CreateModel(
            name='RegistrationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=8, unique=True)),
                ('assigned_to', models.CharField(blank=True, max_length=150)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_registration_codes', to=settings.AUTH_USER_MODEL)),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redeemed_registration_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
