# Generated by Django 6.1.1 on 2026-09-26 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_remove_module_practice_code_participant_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('signup', 'Signup'), ('module_created', 'Module created'), ('module_deleted', 'Module deleted'), ('quiz_hosted', 'Quiz hosted'), ('quiz_ended', 'Quiz ended'), ('quiz_joined', 'Quiz joined'), ('user_created', 'User created'), ('user_updated', 'User updated'), ('user_deleted', 'User deleted'), ('session_ended', 'Session ended'), ('report_downloaded', 'Report downloaded'), ('bank_added', 'Bank question imported'), ('question_banked', 'Question saved to bank'), ('profile_updated', 'Profile updated'), ('password_changed', 'Password changed')], max_length=30),
        ),
        migrations.DeleteModel(
            name='RegistrationCode',
        ),
    ]
