# Generated by Django 6.1.1 on 2026-09-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_user_is_archived_teacherutil'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='api_token',
            field=models.CharField(blank=True, editable=False, help_text='Mobile app ticket binding a device to this play.', max_length=64, null=True, unique=True),
        ),
    ]
